apiVersion: kudobridge.dev/v1alpha1
kind: BridgeInstance
metadata:
  name: service
  namespace: default
  labels:
    group: "cassandra.datastax.com"
    version: "v1beta1"
    kind: "CassandraDatacenter"
  finalizers:
    - finalizer.bridge.kudo.dev
spec:
  kudoOperator:
    package: cassandra
    repository: https://kudo-repository.storage.googleapis.com/0.10.0
    version: 1.0.0
    appVersion: 3.11.6
  crdSpec:
    apiVersion: cassandra.datastax.com/v1beta1
    kind: CassandraDatacenter
    metadata:
      name: dc1
    spec:
      clusterName: cluster1
      serverType: cassandra
      serverVersion: "3.11.6"
      managementApiAuth:
        insecure: {}
      memory: NODE_MEM_MIB
      size: NODE_COUNT
      storageConfig:
        cassandraDataVolumeClaimSpec:
          storageClassName: server-storage
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
      config:
        cassandra-yaml:
          authenticator: org.apache.cassandra.auth.PasswordAuthenticator
          authorizer: org.apache.cassandra.auth.CassandraAuthorizer
          role_manager: org.apache.cassandra.auth.CassandraRoleManager
        jvm-options:
          initial_heap_size: "800M"
          max_heap_size: "800M"
status: {}
